version: '3.8'
services:
  db:
    image: bitnami/postgresql:latest
    container_name: my_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=yourpassword
      - POSTGRESQL_DATABASE=medical_system1
    ports:
      - "5432:5432"
